### PR TITLE
Update SiDroid upload instructions to new app.

### PR DESCRIPTION
**Pull request by yogevm15**
Hi,
I built android app to simplify upload from SiDroid to OResults.

It will be nice to have the instructions in the official OResults documentation.

[Link to play store](https://play.google.com/store/apps/details?id=com.yogevm15.sidroid_oresults_connector)
[Link to source code](https://github.com/yogevm15/sidroid_oresults_connector)

Many thanks,
Maayan

### CODE REVIEW

**Comment by lukaskett** [comment]
Hi,

it looks very good and smart idea to use result service as data source instead of automatic file export. I tried to test your app but I failed with SI Droid bug I guess. I am in touch with the SI Droid app developer.

The result service doesn't return data after few requests on my device. So when I configure and start your app I get error `Error, SiDroid result service not running!`. The service is running but it doesn't return data.

**Comment by yogevm15** [comment]
Hi,

I'm truly sorry for the inconvenience. Apparently, The problem appeared to be with my app. However, I have now resolved this problem, and everything is working fine. The updated app is already available on GitHub, but please note that it might take several hours for it to be published on the Google Play Store.

Best regards,
Maayan

**Comment by yogevm15** [comment]
> Hi,
> 
> it looks very good and smart idea to use result service as data source instead of automatic file export. I tried to test your app but I failed with SI Droid bug I guess. I am in touch with the SI Droid app developer.
> 
> The result service doesn't return data after few requests on my device. So when I configure and start your app I get error `Error, SiDroid result service not running!`. The service is running but it doesn't return data.

Hi,

I'm truly sorry for the inconvenience. Apparently, The problem appeared to be with my app. However, I have now resolved this problem, and everything is working fine. The updated app is already available on GitHub, but please note that it might take several hours for it to be published on the Google Play Store.

Best regards,
Maayan

**Comment by lukaskett** [comment]
Fine, i will give it a try. Could you please specify in detail what was the issue about? I would like to understand it, thanks :) .

**Comment by yogevm15** [comment]
Sure, it was a permission issue. I added these two lines to the Android manifest file:

```xml
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
```

I didn't notice the issue in the production version because I was testing the app in debug mode where the permission wasn't needed😅.

Thanks for giving it a try. I really appreciate it. 🙏🏻

**Comment by lukaskett** [comment]
> Sure, it was a permission issue. I added these two lines to the Android manifest file:
> 
> I didn't notice the issue in the production version because I was testing the app in debug mode where the permission wasn't needed😅.

Thanks for the explanation. Unfortunatelly I am not able to run successfull upload. I still get the same errors while running the service on port 8000. My api key contains `-` as the last character, can it cause an issue? I installed apk from the latest release.

**Comment by lukaskett** [comment]
Fine, with the app from Google Play it finally works👌. Good job! I maybe installed wrong version yesterday.

I found out that the upload doesn't work if SI Droid app isn't openeded (is active in the background).

I guess it's SI Droid app issue because result service icon in the status bar (top of the screen) disappears after a while when the app is running in the background. When you open SI Droid app the result service starts again (icon and notification are visible). Could you please test this behaviour on your device as well?

**Comment by lukaskett** [comment]
It's confirmed. Result service is not running in the background at this moment (is tied to the state of the app) as opposed to read-out that runs in the background. That means you will never get successful upload while having opened your connector app (SI Droid result service is down). You need to have the SI Droid app open for this to work - your app works fine in the background :thumbsup:.

**Comment by yogevm15** [comment]
Weird, with my device SiDroid results service works fine in the background, and even when SiDroid app is closed

**Comment by Jurda5** [comment]
Hi guys :wave: 

Thanks @lukaskett for the testing. I just tried the application and it's working well. I tested it on Samsung Galaxy S22 with Android 13 and I did not experienced any issues with SIdroid even with the phone locked, unlocked etc. :ok_hand: 

Thank you very much @yogevm15 for the app. I am sure it will be greatly appreciated by all organizers using OResults. :pray: 

I will now merge your pull request.

**Review by Jurda5 — APPROVED** [review]

**Pull request merged**
